### ISSUE TITLE
「一人プレイ（オフライン）」などをタップしても反応しない (iPad mini)

### ISSUE THREAD

**Issue by tempest200903** [machikoshian/saikoro#1]
2017/06/10 iPad mini, iOS 10.3.2, Safari 
「一人プレイ（オフライン）」「「一人プレイ（ネット通信）」「二人プレイ（実験中）」
をタップしても反応ありませんでした。

![e4cmu_v7 jpg-large](https://user-images.githubusercontent.com/2082263/27000828-5c22650e-4df5-11e7-9535-894fcf5593d6.jpeg)

**Comment by tempest200903** [comment]
tempest200903 = しめい ( https://twitter.com/simei_gg )

**Comment by tempest200903** [comment]
2017/06/10 16:25 最新版試しました。「タップしても反応しない」でした。

**Comment by tempest200903** [comment]
訂正します。
 iOS 10.3.2 ではなく iOS 9.3.5

**Comment by tempest200903** [comment]
「iOS SafariのWebインスペクタをMac Safariで表示してデバッグする」の方法でコンソールを見てみます。
error 1 個。
 しめい
 「saikoro_client.js:95SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.」

![2017-06-10 17 48 20](https://user-images.githubusercontent.com/2082263/27002399-2f533626-4e1c-11e7-8bb1-077cc132b744.png)

**Comment by machikoshian** [comment]
ありがとうございます。修正したもので更新しましたので、確認していただけませんか？

JavaScript の const を使っていたのが原因でした。iOS 9.3.5 の Safari ではまだ対応していないようでした。下記の変更で修正できていると思います。

https://github.com/machikoshian/saikoro/commit/11df6310df8730d6772a10ecee7b5848873adb62

**Comment by tempest200903** [comment]
2017/06/11 19:10 最新版試しました。
解消しています。サイコロ振ったりもできます。

by しめい
